import { getRoute } from '../../config/routes.js';
import { MissionSession } from '../../domain/MissionSession.js';
import { Backdrop } from '../systems/Backdrop.js';
import { SpawnDirector } from '../systems/SpawnDirector.js';
import { Hud } from '../ui/Hud.js';
const ENEMY_POINTS={scout:100,raider:220,interceptor:170};
export class GameScene extends Phaser.Scene {
  constructor(){super('game');}
  init(data){this.route=getRoute(data.routeId);this.session=new MissionSession(this.route);this.finished=false;this.pointerY=null;this.lastFire=-9999;this.invulnerableUntil=0;this.shieldUntil=0;this.rapidUntil=0;this.nextEnemyShot=0;}
  create(){this.audio=this.registry.get('audio');this.backdrop=new Backdrop(this,this.route);this.director=new SpawnDirector(this.route);this.hud=new Hud(this,this.route);this.player=this.physics.add.image(155,360,'player').setCollideWorldBounds(true).setDepth(20);this.player.body.setSize(78,40,true);
    this.enemies=this.physics.add.group({maxSize:50});this.bolts=this.physics.add.group({maxSize:70});this.enemyBolts=this.physics.add.group({maxSize:45});this.parcels=this.physics.add.group({maxSize:16});this.powerups=this.physics.add.group({maxSize:8});this.sparks=this.add.group({maxSize:80});
    this.cursors=this.input.keyboard?.createCursorKeys()??null;this.up=this.input.keyboard?.addKey('W')??null;this.down=this.input.keyboard?.addKey('S')??null;this.fireKey=this.input.keyboard?.addKey('SPACE')??null;this.fireKey?.on('down',this.fire,this);this.input.on('pointermove',this.pointerMove,this);this.input.on('pointerdown',this.pointerDown,this);
    this.physics.add.overlap(this.bolts,this.enemies,(b,e)=>this.hitEnemy(b,e));this.physics.add.overlap(this.player,this.enemyBolts,(_p,b)=>this.damage(b));this.physics.add.overlap(this.player,this.enemies,(_p,e)=>this.damage(e));this.physics.add.overlap(this.player,this.parcels,(_p,p)=>this.collectParcel(p));this.physics.add.overlap(this.player,this.powerups,(_p,p)=>this.collectPowerup(p));
    this.events.once('shutdown',this.shutdown,this);this.registry.get('platform').gameplayStart();this.cameras.main.fadeIn(200,5,15,26);
  }
  update(time,delta){if(this.finished)return;this.backdrop.update(delta,1+this.session.score/13000);this.movePlayer(delta);this.session.tick(delta);const progress=1-this.session.remainingMs/(this.route.durationSeconds*1000);this.director.update(delta,progress,{enemy:k=>this.spawnEnemy(k,time),parcel:()=>this.spawnParcel(),powerup:k=>this.spawnPowerup(k)});this.updateEnemies(time);this.cleanup();this.hud.update(this.session,this.powerLabel(time));if(this.session.ended)this.finish();}
  movePlayer(delta){const up=this.cursors?.up.isDown||this.up?.isDown,down=this.cursors?.down.isDown||this.down?.isDown,s=this.route.playerSpeed;if(up){this.player.setVelocityY(-s);this.pointerY=null;}else if(down){this.player.setVelocityY(s);this.pointerY=null;}else if(this.pointerY!==null){const diff=this.pointerY-this.player.y;this.player.setVelocityY(Math.abs(diff)<6?0:Phaser.Math.Clamp(diff*6.4,-s,s));}else this.player.setVelocityY(0);const body=this.player.body;this.player.setAngle(Phaser.Math.Clamp(body.velocity.y/s,-1,1)*8);this.player.x=Phaser.Math.Linear(this.player.x,155,Math.min(1,delta*.004));}
  spawnEnemy(kind,time){const texture=kind;const y=Phaser.Math.Between(135,this.scale.height-100),e=this.enemies.get(this.scale.width+100,y,texture);if(!e)return;e.enableBody(true,this.scale.width+100,y,true,true);e.setScale(1).setAlpha(1).clearTint().setDepth(15);e.setData({kind,hp:kind==='raider'?2:1,bornAt:time,baseY:y,nextShot:time+Phaser.Math.Between(850,1600)});const base=kind==='interceptor'?330:kind==='scout'?250:185;e.setVelocityX(-base*this.route.speedMultiplier);e.body.setSize(kind==='raider'?82:kind==='interceptor'?68:62,kind==='raider'?44:36,true);}
  updateEnemies(time){this.enemies.children.iterate(e=>{if(!e?.active)return;const kind=e.getData('kind'),age=(time-e.getData('bornAt'))/1000;if(kind==='interceptor')e.y=e.getData('baseY')+Math.sin(age*4.2)*82;if(kind==='raider'&&e.x<this.scale.width-120&&time>=e.getData('nextShot')){this.enemyFire(e);e.setData('nextShot',time+Phaser.Math.Between(1100,1900));}});}
  spawnParcel(){const y=Phaser.Math.Between(145,this.scale.height-105),p=this.parcels.get(this.scale.width+70,y,'parcel');if(!p)return;p.enableBody(true,this.scale.width+70,y,true,true);p.setScale(1).setAlpha(1).setVelocityX(-190*this.route.speedMultiplier).setAngularVelocity(28).setDepth(14);}
  spawnPowerup(kind){const y=Phaser.Math.Between(150,this.scale.height-110),p=this.powerups.get(this.scale.width+70,y,kind);if(!p)return;p.enableBody(true,this.scale.width+70,y,true,true);p.setTexture(kind).setScale(1).setAlpha(1).setVelocityX(-170*this.route.speedMultiplier).setAngularVelocity(42).setData('kind',kind).setDepth(14);}
  fire(){const time=this.time.now,cooldown=time<this.rapidUntil?105:220;if(this.finished||time-this.lastFire<cooldown)return;const b=this.bolts.get(this.player.x+58,this.player.y,'bolt');if(!b)return;this.lastFire=time;b.enableBody(true,this.player.x+58,this.player.y,true,true);b.setScale(1).setAlpha(1).setVelocityX(900).setDepth(18);this.audio.play('fire');}
  enemyFire(enemy){const b=this.enemyBolts.get(enemy.x-38,enemy.y,'enemy-bolt');if(!b)return;b.enableBody(true,enemy.x-38,enemy.y,true,true);b.setScale(1).setAlpha(1).setDepth(17);this.physics.moveToObject(b,this.player,300*this.route.speedMultiplier);}
  hitEnemy(b,e){if(!b.active||!e.active)return;b.disableBody(true,true);const hp=e.getData('hp')-1;e.setData('hp',hp);this.burst(e.x,e.y,hp<=0?0xffd36f:0xffffff,hp<=0?12:5);this.audio.play('hit');if(hp>0){e.setTintFill(0xffffff);this.time.delayedCall(65,()=>e.active&&e.clearTint());return;}const points=this.session.destroyEnemy(ENEMY_POINTS[e.getData('kind')]);this.floatText(e.x,e.y,`+${points}`);e.disableBody(true,true);}
  collectParcel(p){if(!p.active)return;p.disableBody(true,true);const points=this.session.collectParcel();this.audio.play('pickup');this.burst(this.player.x+35,this.player.y,0x72f6b8,15);this.floatText(this.player.x+95,this.player.y-28,`DELIVERED +${points}`);}
  collectPowerup(p){if(!p.active)return;const kind=p.getData('kind');p.disableBody(true,true);if(kind==='shield'){this.shieldUntil=this.time.now+7000;this.audio.play('shield');this.player.setTint(0x8eeeff);}else{this.rapidUntil=this.time.now+8000;this.audio.play('rapid');}this.floatText(this.player.x+90,this.player.y-35,kind==='shield'?'SHIELD 7s':'RAPID FIRE 8s');}
  damage(source){if(!source.active||this.finished)return;source.disableBody(true,true);if(this.time.now<this.shieldUntil){this.shieldUntil=0;this.player.clearTint();this.audio.play('shield');this.burst(this.player.x,this.player.y,0x72e8ff,18);return;}if(this.time.now<this.invulnerableUntil)return;this.invulnerableUntil=this.time.now+900;this.session.takeDamage();this.audio.play('damage');this.cameras.main.shake(160,.012);this.cameras.main.flash(150,255,70,85);this.burst(this.player.x,this.player.y,0xff7184,18);this.tweens.add({targets:this.player,alpha:.2,duration:90,yoyo:true,repeat:5,onComplete:()=>this.player.setAlpha(1)});}
  cleanup(){for(const e of this.enemies.getChildren())if(e.active&&e.x<-125){e.disableBody(true,true);this.session.combo=Math.max(1,this.session.combo-.25);}for(const b of this.bolts.getChildren())if(b.active&&b.x>this.scale.width+90)b.disableBody(true,true);for(const b of this.enemyBolts.getChildren())if(b.active&&(b.x<-70||b.y<-70||b.y>this.scale.height+70))b.disableBody(true,true);for(const p of this.parcels.getChildren())if(p.active&&p.x<-75){p.disableBody(true,true);this.session.missParcel();}for(const p of this.powerups.getChildren())if(p.active&&p.x<-75)p.disableBody(true,true);}
  powerLabel(time){if(time<this.shieldUntil)return`SHIELD ${Math.ceil((this.shieldUntil-time)/1000)}s`;if(this.shieldUntil>0){this.shieldUntil=0;this.player.clearTint();}if(time<this.rapidUntil)return`RAPID ${Math.ceil((this.rapidUntil-time)/1000)}s`;return'';}
  finish(){if(this.finished)return;this.finished=true;this.registry.get('platform').gameplayStop();const result=this.session.snapshot();this.registry.get('progress').saveResult(result);this.audio.play(result.success?'success':'failure');this.cameras.main.fadeOut(320,5,15,26);this.time.delayedCall(340,()=>this.scene.start('result',result));}
  floatText(x,y,msg){const t=this.add.text(x,y,msg,{fontFamily:'Arial Black',fontSize:'21px',color:'#fff',stroke:'#091525',strokeThickness:5}).setOrigin(.5).setDepth(80);this.tweens.add({targets:t,y:y-55,alpha:0,duration:650,ease:'Cubic.out',onComplete:()=>t.destroy()});}
  burst(x,y,color,count){for(let i=0;i<count;i++){const s=this.add.image(x,y,'spark').setTint(color).setDepth(40),a=Phaser.Math.FloatBetween(0,Math.PI*2),d=Phaser.Math.Between(30,95);this.tweens.add({targets:s,x:x+Math.cos(a)*d,y:y+Math.sin(a)*d,scale:0,alpha:0,duration:Phaser.Math.Between(250,520),ease:'Cubic.out',onComplete:()=>s.destroy()});}}
  pointerMove(p){this.pointerY=Phaser.Math.Clamp(p.y,125,this.scale.height-80);}pointerDown(p){this.pointerY=Phaser.Math.Clamp(p.y,125,this.scale.height-80);this.fire();}
  shutdown(){this.registry.get('platform').gameplayStop();this.fireKey?.off('down',this.fire,this);this.input.off('pointermove',this.pointerMove,this);this.input.off('pointerdown',this.pointerDown,this);}
}
