export const ROUTES = Object.freeze([
  Object.freeze({
    id: 'downtown',
    order: 0,
    name: 'DOWNTOWN DASH',
    subtitle: 'Morning courier lane',
    briefing: 'DENSE TRAFFIC · LIGHT PATROL',
    durationSeconds: 45,
    targetParcels: 6,
    lives: 3,
    playerSpeed: 460,
    enemySpawnStartMs: 980,
    enemySpawnMinMs: 520,
    parcelSpawnMs: 4000,
    powerupSpawnMs: 15000,
    speedMultiplier: 1,
    enemyWeights: Object.freeze({ scout: 0.64, raider: 0.28, interceptor: 0.08 }),
    stars: Object.freeze({ two: 4800, three: 7600 }),
    openingDurationMs: 8800,
    openingEvents: Object.freeze([
      Object.freeze({ atMs: 650, type: 'parcel' }),
      Object.freeze({ atMs: 1500, type: 'enemy', kind: 'scout' }),
      Object.freeze({ atMs: 2450, type: 'parcel' }),
      Object.freeze({ atMs: 3400, type: 'enemy', kind: 'scout' }),
      Object.freeze({ atMs: 4550, type: 'powerup', kind: 'rapid' }),
      Object.freeze({ atMs: 5850, type: 'parcel' }),
      Object.freeze({ atMs: 7100, type: 'enemy', kind: 'raider' }),
    ]),
    scenery: Object.freeze({
      cloudCount: 7,
      cloudAlpha: 0.14,
      cloudSpeed: 7,
      starCount: 0,
      trafficCount: 12,
      trafficColor: 0xffd36f,
      accentColor: 0x79f3ff,
      hazeAlpha: 0.10,
      water: null,
      landmarks: Object.freeze([
        Object.freeze({ kind: 'billboard', x: 0.20, y: 0.57, scale: 1.0 }),
        Object.freeze({ kind: 'antenna', x: 0.72, y: 0.48, scale: 0.9 }),
        Object.freeze({ kind: 'billboard', x: 0.87, y: 0.62, scale: 0.72 }),
      ]),
    }),
    palette: Object.freeze({
      top: 0x102b4a,
      middle: 0x246185,
      bottom: 0x57a4bd,
      sun: 0xffd77a,
      celestialRadius: 62,
      far: 0x173653,
      near: 0x11273f,
    }),
  }),
  Object.freeze({
    id: 'harbor',
    order: 1,
    name: 'HARBOR EXPRESS',
    subtitle: 'Crosswind cargo route',
    briefing: 'CROSSWIND · ARMED RAIDERS',
    durationSeconds: 52,
    targetParcels: 8,
    lives: 3,
    playerSpeed: 485,
    enemySpawnStartMs: 850,
    enemySpawnMinMs: 440,
    parcelSpawnMs: 3600,
    powerupSpawnMs: 13500,
    speedMultiplier: 1.15,
    enemyWeights: Object.freeze({ scout: 0.46, raider: 0.37, interceptor: 0.17 }),
    stars: Object.freeze({ two: 6800, three: 9800 }),
    openingDurationMs: 9000,
    openingEvents: Object.freeze([
      Object.freeze({ atMs: 550, type: 'parcel' }),
      Object.freeze({ atMs: 1300, type: 'enemy', kind: 'scout' }),
      Object.freeze({ atMs: 2250, type: 'enemy', kind: 'raider' }),
      Object.freeze({ atMs: 3250, type: 'parcel' }),
      Object.freeze({ atMs: 4250, type: 'powerup', kind: 'shield' }),
      Object.freeze({ atMs: 5600, type: 'enemy', kind: 'interceptor' }),
      Object.freeze({ atMs: 6750, type: 'parcel' }),
      Object.freeze({ atMs: 7850, type: 'enemy', kind: 'raider' }),
    ]),
    scenery: Object.freeze({
      cloudCount: 5,
      cloudAlpha: 0.18,
      cloudSpeed: 10,
      starCount: 0,
      trafficCount: 7,
      trafficColor: 0xb5fff0,
      accentColor: 0x67f0d1,
      hazeAlpha: 0.15,
      water: Object.freeze({ y: 0.80, color: 0x103f57, highlight: 0x62d7dc }),
      landmarks: Object.freeze([
        Object.freeze({ kind: 'crane', x: 0.22, y: 0.55, scale: 1.1 }),
        Object.freeze({ kind: 'crane', x: 0.58, y: 0.58, scale: 0.86 }),
        Object.freeze({ kind: 'antenna', x: 0.84, y: 0.49, scale: 0.75 }),
      ]),
    }),
    palette: Object.freeze({
      top: 0x163b57,
      middle: 0x237783,
      bottom: 0x4fb4aa,
      sun: 0xffe0a0,
      celestialRadius: 58,
      far: 0x19485a,
      near: 0x11333e,
    }),
  }),
  Object.freeze({
    id: 'night',
    order: 2,
    name: 'MIDNIGHT PRIORITY',
    subtitle: 'High-risk express lane',
    briefing: 'HIGH SPEED · HEAVY FIRE',
    durationSeconds: 60,
    targetParcels: 10,
    lives: 3,
    playerSpeed: 510,
    enemySpawnStartMs: 760,
    enemySpawnMinMs: 360,
    parcelSpawnMs: 3300,
    powerupSpawnMs: 12000,
    speedMultiplier: 1.32,
    enemyWeights: Object.freeze({ scout: 0.30, raider: 0.42, interceptor: 0.28 }),
    stars: Object.freeze({ two: 9000, three: 12800 }),
    openingDurationMs: 8400,
    openingEvents: Object.freeze([
      Object.freeze({ atMs: 450, type: 'parcel' }),
      Object.freeze({ atMs: 1050, type: 'enemy', kind: 'interceptor' }),
      Object.freeze({ atMs: 1850, type: 'enemy', kind: 'scout' }),
      Object.freeze({ atMs: 2750, type: 'parcel' }),
      Object.freeze({ atMs: 3550, type: 'enemy', kind: 'raider' }),
      Object.freeze({ atMs: 4450, type: 'powerup', kind: 'rapid' }),
      Object.freeze({ atMs: 5400, type: 'enemy', kind: 'interceptor' }),
      Object.freeze({ atMs: 6450, type: 'parcel' }),
      Object.freeze({ atMs: 7450, type: 'enemy', kind: 'raider' }),
    ]),
    scenery: Object.freeze({
      cloudCount: 3,
      cloudAlpha: 0.08,
      cloudSpeed: 15,
      starCount: 42,
      trafficCount: 18,
      trafficColor: 0xff6f9f,
      accentColor: 0x8c9cff,
      hazeAlpha: 0.06,
      water: null,
      landmarks: Object.freeze([
        Object.freeze({ kind: 'antenna', x: 0.18, y: 0.44, scale: 1.2 }),
        Object.freeze({ kind: 'billboard', x: 0.52, y: 0.60, scale: 0.88 }),
        Object.freeze({ kind: 'antenna', x: 0.82, y: 0.50, scale: 0.95 }),
      ]),
    }),
    palette: Object.freeze({
      top: 0x080f2c,
      middle: 0x15204d,
      bottom: 0x293d69,
      sun: 0xc9dcff,
      celestialRadius: 40,
      far: 0x101a39,
      near: 0x090f27,
    }),
  }),
]);

export function getRoute(routeId) {
  const route = ROUTES.find((candidate) => candidate.id === routeId);
  if (!route) throw new Error(`Unknown route: ${routeId}`);
  return route;
}

export function getNextRoute(routeId) {
  const current = getRoute(routeId);
  return ROUTES[current.order + 1] ?? null;
}
